# Generated by Django 5.0.7 on 2025-09-25 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_passwordresettoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='color_primary',
            field=models.CharField(blank=True, default='#0a75ff', max_length=20),
        ),
        migrations.AddField(
            model_name='tenant',
            name='color_secondary',
            field=models.CharField(blank=True, default='#0f172a', max_length=20),
        ),
        migrations.AddField(
            model_name='tenant',
            name='logo_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
