# Generated by Django 5.0.7 on 2025-09-28 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_plan_tenant_is_active_tenant_region_apikey_auditlog_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PricingAgreement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount_cents", models.PositiveIntegerField()),
                ("currency", models.CharField(default="EUR", max_length=3)),
                ("period", models.CharField(default="monthly", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "org",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pricing_agreements",
                        to="core.tenant",
                    ),
                ),
                (
                    "subspace",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pricing_agreements",
                        to="core.subspace",
                    ),
                ),
            ],
            options={
                "unique_together": {("org", "subspace", "currency", "period")},
            },
        ),
    ]
